#!/bin/bash
# GetTemplateImages from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

baseurl="https://wiki.ubuntuusers.de/"
midurl="Wiki/Vorlagen/"
metaurl="/a/export/meta"
imgurl="_image?target="
tpl_array=(Installbutton PPA StatusIcon Tasten)

if [ ! -d Vorlagen ]
  then
    echo "Creating folder \"Vorlagen\"..."
    mkdir Vorlagen
fi
rm -r ./Vorlagen/*
cd Vorlagen

for tpl in "${tpl_array[@]}"
do
  if [ ! -d ${tpl} ]
    then
      echo "Creating folder \"${tpl}\"..."
      mkdir ${tpl}
  fi
  cd ${tpl}

  xattach=($(wget -qO- "${baseurl}${midurl}${tpl}${metaurl}" | grep -Eo "${midurl}${tpl}/[0-9a-zA-Z._-]*\.(jpe?g|png|bmp|gif|svg|tiff|tif)"))
  for i in "${xattach[@]}"
  do
    basename="${i##*/}"
    wget -nv "${baseurl}${imgurl}${i}" -O $basename
  done
  cd ..
done

cd ..
echo "DOWNLOAD OF WIKI TEMPLATE IMAGES FINISHED"
