#!/bin/bash
# GetWikiIcons from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

baseurl="https://wiki.ubuntuusers.de/"
midurl="Wiki/Icons/"
metaurl="/a/export/meta"
imgurl="_image?target="
# Icons which are NOT stored in subfolders
icon_array_nosub=(Linux Hardware System Sonstige)
# Icons which are stored in subfolders
icon_array_sub=(Portal Protokolle Tango Oxygen Breeze)

if [ ! -d Icons ]
  then
    echo "Creating folder \"Wiki\Icons\"..."
    mkdir Icons
fi
rm -r ./Icons/*
cd Icons

for ico in "${icon_array_nosub[@]}"
do
  xattach=($(wget -qO- "${baseurl}${midurl}${ico}${metaurl}" | grep -Eo "${midurl}[0-9a-zA-Z._-]*\.(jpe?g|png|bmp|gif|svg|tiff|tif)"))
  for i in "${xattach[@]}"
  do
    basename="${i##*/}"
    wget -nv "${baseurl}${imgurl}${i}" -O $basename
  done
done

for ico in "${icon_array_sub[@]}"
do
  if [ ! -d ${ico} ]
    then
      echo "Creating folder \"${ico}\"..."
      mkdir ${ico}
  fi
  cd ${ico}
  
  xattach=($(wget -qO- "${baseurl}${midurl}${ico}${metaurl}" | grep -Eo "${midurl}${ico}/[0-9a-zA-Z._-]*\.(jpe?g|png|bmp|gif|svg|tiff|tif)"))
  for i in "${xattach[@]}"
  do
    basename="${i##*/}"
    wget -nv "${baseurl}${imgurl}${i}" -O $basename
  done
  cd ..
done

cd ..
echo "DOWNLOAD OF WIKI ICONS FINISHED"
