#!/bin/bash
# GetIWLs from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

PROJECT="${1}"

if [ "${PROJECT}" == "" ]
  then
    echo "USAGE: ./`basename $0` [STYLES FOLDER]"
    exit
fi

if [ ! -d ${PROJECT} ]
  then
    echo "Creating styles main folder..."
    mkdir -p ${PROJECT}
fi
cd ${PROJECT}

if [ ! -d styles ]
  then
    echo "Creating folder \"styles\"..."
    mkdir styles
fi
cd styles

echo "Downloading css files..."
rm main.css
rm markup2.css
rm wiki.css
rm highlight.css
rm markup.css

wget -nv https://static-cdn.ubuntu-de.org/style/main.css
wget -nv https://static-cdn.ubuntu-de.org/style/markup.css
mv markup.css markup2.css
wget -nv https://static-cdn.ubuntu-de.org/style/wiki.css
wget -nv https://static-cdn.ubuntu-de.org/style/highlight.css
wget -nv https://ubuntuusers.de/markup.css

echo "Replace static paths..."
## Paths
_r1="//media-cdn.ubuntu-de.org/wiki/attachments/[0-9][0-9]/[0-9][0-9]"
_r2="../img/interwiki"
## Escape path for sed using bash find and replace
_r1="${_r1//\//\\/}"
_r2="${_r2//\//\\/}"
## Replace paths
sed -e "s/${_r1}/${_r2}/g" -i markup.css

cd ..

if [ ! -d font ]
  then
    echo "Creating folder \"font\"..."
    mkdir font
fi
cd font

if [ ! -d Liberation_webkit_macroman ]
  then
    mkdir Liberation_webkit_macroman
fi
cd Liberation_webkit_macroman

if [ ! -d Sans ]
  then
    mkdir Sans
fi
cd Sans

if [ ! -d Regular ]
  then
    mkdir Regular
fi
cd Regular
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Regular/LiberationSans-Regular-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Regular/LiberationSans-Regular-webfont.ttf

cd ..
if [ ! -d Italic ]
  then
    mkdir Italic
fi
cd Italic
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Italic/LiberationSans-Italic-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Italic/LiberationSans-Italic-webfont.ttf

cd ..
if [ ! -d Bold ]
  then
    mkdir Bold
fi
cd Bold
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Bold/LiberationSans-Bold-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Bold/LiberationSans-Bold-webfont.ttf

cd ..
if [ ! -d BoldItalic ]
  then
    mkdir BoldItalic
fi
cd BoldItalic
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/BoldItalic/LiberationSans-BoldItalic-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/BoldItalic/LiberationSans-BoldItalic-webfont.ttf

cd ..
cd ..
if [ ! -d Mono ]
  then
    mkdir Mono
fi
cd Mono
if [ ! -d Regular ]
  then
    mkdir Regular
fi
cd Regular
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Mono/Regular/LiberationMono-Regular-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Mono/Regular/LiberationMono-Regular-webfont.ttf

cd ..
cd ..
cd ..
if [ ! -d uude-font-0.83 ]
  then
    mkdir uude-font-0.83
fi
cd uude-font-0.83
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-bold.woff2
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-bold.woff
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-bold.ttf
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-light.woff2
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-light.woff
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-light.ttf

cd ..
cd ..
if [ ! -d img ]
  then
    echo "Creating folder \"img\"..."
    mkdir img
fi
cd img

if [ ! -d interwiki ]
  then
    echo "Creating folder \"interwiki\"..."
    mkdir interwiki
fi
cd interwiki

wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/archwiki.png -O archwiki.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/askubuntu.png -O askubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/bitbucket.png -O bitbucket.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/blogspot.png -O blogspot.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/box.png -O box.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/bug.png -O bug.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/calendar.png -O calendar.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonical.png -O canonical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonicalblog.png -O canonicalblog.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonicalvoices.png -O canonicalvoices.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debian.png -O debian.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debianbug.png -O debianbug.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debian_de.png -O debian_de.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/derstandard.png -O derstandard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/desura.png -O desura.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/diaspora.png -O diaspora.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/dropbox.png -O dropbox.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/duckduckgo.png -O duckduckgo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ean.png -O ean.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/edubuntu.png -O edubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/fb.png -O fb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freedesktop.png -O freedesktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freenode.png -O freenode.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freshmeat.png -O freshmeat.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnomeapps.png -O gnomeapps.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnomeprojects.png -O gnomeprojects.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/getdeb.png -O getdeb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/github.png -O github.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnome.png -O gnome.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gog.png -O gog.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/googlecode.png -O googlecode.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/heise.png -O heise.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/holarse.png -O holarse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/humble.png -O humble.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/iawm.png -O iawm.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ikhaya.png -O ikhaya.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/indiedb.png -O indiedb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/identica.png -O identica.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/isbn.png -O isbn.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ixquick.png -O ixquick.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kdebugs.png -O kdebugs.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu.png -O kubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu-de.png -O kubuntu-de.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu_doc.png -O kubuntu_doc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lastfm.png -O lastfm.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/launchpad.png -O launchpad.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/launchpad2.png -O launchpad2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lgdb.png -O lgdb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/liflg.jpg -O liflg.jpg
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/linuxgaming.png -O linuxgaming.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lpcode.png -O lpcode.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lpuser.png -O lpuser.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lubuntu.png -O lubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/man.png -O man.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/man_de.png -O man_de.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ml.png -O ml.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/moby.png -O moby.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/moddb.png -O moddb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/mythbuntu.png -O mythbuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/omgubuntu.png -O omgubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/openstore.png -O openstore.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/opensuse.jpg -O opensuse.jpg
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/osm.png -O osm.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/packages.png -O packages.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/paste.png -O paste.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ppa.png -O ppa.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/playdeb.png -O playdeb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/prolinux.png -O prolinux.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/quakenet.png -O quakenet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/selfhtmlwiki.png -O selfhtmlwiki.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/sourceforge.png -O sourceforge.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/sourceforge2.png -O sourceforge2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/stackoverflow.png -O stackoverflow.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/startpage.png -O startpage.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/steam.png -O steam.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/team.png -O team.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ticket.png -O ticket.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/twitter.png -O twitter.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uappexplorer.png -O uappexplorer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu.png -O ubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntuapps.png -O ubuntuapps.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_forum.png -O uf_forum.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_member.png -O uf_member.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_thread.png -O uf_thread.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntufridge.png -O ubuntufridge.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubunturesources.png -O ubunturesources.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntumate.png -O ubuntumate.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntusub.png -O ubuntusub.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntugnome.png -O ubuntugnome.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntustudio.png -O ubuntustudio.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu_doc.png -O ubuntu_doc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu_fr.png -O ubuntu_fr.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/user.png -O user.png
cp user.png user-xmas.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/vimeo.png -O vimeo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikibooks.png -O wikibooks.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikibooks_en.png -O wikibooks_en.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikimedia.png -O wikimedia.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikipedia.png -O wikipedia.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikipedia_en.png -O wikipedia_en.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wordpress.png -O wordpress.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/xfcedocs.png -O xfcedocs.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/xubuntu.png -O xubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/youtube.png -O youtube.png

wget -nv https://static-cdn.ubuntu-de.org/img/interwiki/search.png -O search.png
wget -nv https://media-cdn.ubuntu-de.org/wiki/attachments/17/43/ppa.png -O ppa.png

echo "IWL DOWNLOAD FINISHED"
