#!/bin/bash
# GetInyokaStyles from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

PROJECT="${1}"

if [ "${PROJECT}" == "" ]
  then
    echo "USAGE: ./`basename $0` [STYLES FOLDER]"
    exit
fi

SCRIPTDIR=$( cd "$( dirname "$0" )" && pwd )

if [ ! -d ${PROJECT} ]
  then
    echo "Creating styles main folder..."
    mkdir -p ${PROJECT}
fi
cd ${PROJECT}

echo "Calling IWL script..."
bash ${SCRIPTDIR}/GetIWLs ${PROJECT}

cd ${PROJECT}
if [ ! -d img ]
  then
    echo "Creating folder \"img\"..."
    mkdir img
fi
cd img

echo "Downloading images..."
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/anchor.png -O anchor.png
wget -nv https://static-cdn.ubuntu-de.org/img/icon-sprite.png -O icon-sprite.png

if [ ! -d wiki ]
  then
    echo "Creating folder \"wiki\"..."
    mkdir wiki
fi
cd wiki

wget -nv https://static-cdn.ubuntu-de.org/img/wiki/toc.png -O toc.png
wget -nv https://media-cdn.ubuntu-de.org/wiki/attachments/42/17/button.png -O button.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/mouse_left.png -O mouse_left.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/mouse_midd.png -O mouse_midd.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/mouse_right.png -O mouse_right.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/menu.png -O menu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/power.png -O power.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/tux.png -O tux.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/ubuntu.png -O ubuntu.png
wget -nv https://static-cdn.ubuntu-de.org/img/wiki/heading.png -O heading.png
cd ..


if [ -d flags ]
  then
    echo "Removing obsolete folder \"flags\"..."
    rm -r flags/
fi
cd ..


if [ ! -d Wiki ]
  then
    echo "Creating folder \"Wiki\"..."
    mkdir Wiki
fi
cd Wiki

if [ ! -d FlaggenMap ]
  then
    echo "Creating folder \"Wiki\FlaggenMap\"..."
    mkdir FlaggenMap
fi
cd FlaggenMap

wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ar.png -O ar.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/at.png -O at.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/au.png -O au.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/be.png -O be.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ca.png -O ca.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cat.png -O cat.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ch.png -O ch.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cl.png -O cl.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cy.png -O cy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cz.png -O cz.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/da.png -O da.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/de.png -O de.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/gb.png -O gb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/eo.png -O eo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/es.png -O es.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/et.png -O et.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/eu.png -O eu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/fi.png -O fi.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/fo.png -O fo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/fr.png -O fr.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/gb.png -O gb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/gd.png -O gd.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/gr.png -O gr.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/hr.png -O hr.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/hu.png -O hu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/id.png -O id.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ie.png -O ie.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/il.png -O il.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ir.png -O ir.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/it.png -O it.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/jp.png -O jp.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ko.png -O ko.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/lv.png -O lv.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ne.png -O ne.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/nl.png -O nl.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/nw.png -O nw.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/pl.png -O pl.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/pt.png -O pt.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ro.png -O ro.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/rs.png -O rs.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ru.png -O ru.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/se.png -O se.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/sk.png -O sk.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/sl.png -O sl.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/sv.png -O sv.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/tr.png -O tr.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/uk.png -O uk.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/us.png -O us.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/uz.png -O uz.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/vi.png -O vi.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/za.png -O za.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/zh.png -O zh.png

cd ..


if [ ! -d Smilies ]
  then
    echo "Creating folder \"Wiki\Smilies\"..."
    mkdir Smilies
fi
cd Smilies


# normal smilies
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/happy.png -O happy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/sad.png -O sad.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/wink.png -O wink.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/razz.png -O razz.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/biggrin.png -O biggrin.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/surprised.png -O surprised.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/confused.png -O confused.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/angry.png -O angry.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/cool.png -O cool.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/redface.gif -O redface.gif
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/favorite.png -O favorite.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/grin.png -O grin.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/canny.png -O canny.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/eek.png -O eek.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/frosch.png -O frosch.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/frosch.png -O frosch-xmas.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/neutral.png -O neutral.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/cry.png -O cry.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/evil.png -O evil.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/twisted.png -O twisted.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/angel.png -O angel.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/smile.png -O smile.png

# text smilies
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/exclaim.png -O exclaim.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/question.png -O question.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/april.png -O april.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/arrow.png -O arrow.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/backarrow.png -O backarrow.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/ente.png -O ente.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/idea.png -O idea.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/lol.png -O lol.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/rolleyes.gif -O rolleyes.gif
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/thumbsup.png -O thumbsup.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/tux.png -O tux.png

# icons
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/download.png -O download.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/ubuntu.png -O ubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/ubuntugnome.png -O ubuntugnome.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/kubuntu.png -O kubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/lubuntu.png -O lubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smiliesmap/ubuntumate.png -O ubuntumate.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/mythbuntu.png -O mythbuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smiliesmap/ubuntutouch.png -O ubuntutouch.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/xubuntu.png -O xubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Smilies/overview.png -O overview.png

cd ..


if [ ! -d Icons ]
  then
    echo "Creating folder \"Wiki\Icons\"..."
    mkdir Icons
fi
cd Icons

# Linux
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu.png -O ubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu64.png -O ubuntu64.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntugnome.png -O ubuntugnome.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntumate.png -O ubuntumate.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/kubuntu.png -O kubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/lubuntu.png -O lubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/xubuntu.png -O xubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/edubuntu.png -O edubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntustudio.png -O ubuntustudio.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mythbuntu.png -O mythbuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/unity.png -O unity.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu_server.png -O ubuntu_server.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntukylin.png -O ubuntukylin.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/kxubuntu.png -O kxubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/brainstorm.png -O brainstorm.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu-community.png -O ubuntu-community.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/canonical.png -O canonical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntutouch.png -O ubuntutouch.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/budgie.png -O budgie.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/UbuntuNetbookEdition.png -O UbuntuNetbookEdition.png

wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome.png -O gnome.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnu.png -O gnu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tux.png -O tux.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/debian.png -O debian.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/arch.png -O arch.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/slackware.png -O slackware.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gentoo.png -O gentoo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/suse.png -O suse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/python.png -O python.png


# Programme
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/calc.png -O calc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/dtp.png -O dtp.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/file-manager.png -O file-manager.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/synaptic.png -O synaptic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/text-editor.png -O text-editor.png

# Hardware
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/2monitors.png -O 2monitors.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/camera.png -O camera.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/computer.png -O computer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/floppy.png -O floppy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/games.png -O games.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hd.png -O hd.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hd-linux.png -O hd-linux.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hd-windows.png -O hd-windows.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ipod-mini-blue.png -O ipod-mini-blue.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ipod-photos.png -O ipod-photos.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/joystick.png -O joystick.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mouse.png -O mouse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mouse2.png -O mouse2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/notebook.png -O notebook.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/pci.png -O pci.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/portablemp3.png -O portablemp3.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/printer.png -O printer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/printer2.png -O printer2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/scanner.png -O scanner.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tv.png -O tv.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tv2.png -O tv2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/usb.png -O usb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/CPU.png -O CPU.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/bluetooth.png -O bluetooth.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/keyboard.png -O keyboard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mouse3.png -O mouse3.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/backup.png -O backup.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/download_manager.png -O download_manager.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/harddrive.png -O harddrive.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/removable-usb.png -O removable-usb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/network_local.png -O network_local.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/networksettings.png -O networksettings.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/removable.png -O removable.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/removable-1394.png -O removable-1394.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/SSD.png -O SSD.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango_Phone.png -O Tango_Phone.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Radio.png -O Radio.png

# System
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/access.png -O access.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/advancedsettings.png -O advancedsettings.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/button_cancel.png -O button_cancel.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/config.png -O config.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/develop.png -O develop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/dvd.png -O dvd.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/globe.png -O globe.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome-cd.png -O gnome-cd.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome-reclevel.png -O gnome-reclevel.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome-warning.png -O gnome-warning.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/help.png -O help.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/home.png -O home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/internet.png -O internet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/konsole2.png -O konsole2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/multimedia.png -O multimedia.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/optical.png -O optical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/search2.png -O search2.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/secure_non.png -O secure_non.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/security.png -O security.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/settings.png -O settings.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/sound.png -O sound.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/soundcontrol.png -O soundcontrol.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/terminal.png -O terminal.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/volume.png -O volume.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/trash.png -O trash.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/service.png -O service.png

# Sonstige
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/background.png -O background.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/blackbox.png -O blackbox.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/box.png -O box.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/burning.png -O burning.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/community-help.png -O community-help.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/contact.png -O contact.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/date.png -O date.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/dtp.png -O dtp.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/email.png -O email.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gear.png -O gear.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hint.png -O hint.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/improvements.png -O improvements.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/looknfeel.png -O looknfeel.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/movies.png -O movies.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/package.png -O package.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/panel.png -O panel.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/pencil.png -O pencil.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/pfeiltasten.png -O pfeiltasten.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/rss.png -O rss.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/save_all.png -O save_all.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/synaptic.png -O synaptic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/time.png -O time.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/wiki.png -O wiki.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/unknown.png -O unknown.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/openstreetmap.png -O openstreetmap.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/users.png -O users.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/windows_users.png -O windows_users.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/window.png -O window.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/win-ubuntu.png -O win-ubuntu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/wubi.png -O wubi.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tasten_wasd.png -O tasten_wasd.png

if [ ! -d Protokolle ]
  then
    echo "Creating folder \"Wiki\Icons\Protokolle\"..."
    mkdir Protokolle
fi
cd Protokolle

# Protokolle
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/aim.png -O aim.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/bonjour.png -O bonjour.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/facebook.png -O facebook.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/gadu-gadu.png -O gadu-gadu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/google.png -O google.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/icq.png -O icq.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/irc.png -O irc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/msn.png -O msn.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/mrim.png -O mrim.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/mxit.png -O mxit.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/myspace.png -O myspace.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/novell.png -O novell.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/qq.png -O qq.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/sametime.png -O sametime.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/silc.png -O silc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/simple.png -O simple.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/vkontakte.png -O vkontakte.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/xmpp.png -O xmpp.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/yahoo.png -O yahoo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/zephyr.png -O zephyr.png

wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/aim-24.png -O aim-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/bonjour-24.png -O bonjour-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/gadu-gadu-24.png -O gadu-gadu-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/icq-24.png -O icq-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/irc-24.png -O irc-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/meanwhile-24.png -O meanwhile-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/mrim-24.png -O mrim-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/msn-24.png -O msn-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/mxit-24.png -O mxit-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/myspace-24.png -O myspace-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/netsoul-24.png -O netsoul-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/novell-24.png -O novell-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/qq-24.png -O qq-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/rss-24.png -O rss-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/sametime-24.png -O sametime-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/silc-24.png -O silc-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/simple-24.png -O simple-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/skype-24.png -O skype-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/sms-24.png -O sms-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/twitter-24.png -O twitter-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/vkontakte-24.png -O vkontakte-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/winpopup-24.png -O winpopup-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/xmpp-24.png -O xmpp-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/yahoo-24.png -O yahoo-24.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/zephyr-24.png -O zephyr-24.png

cd ..

if [ ! -d Tango ]
  then
    echo "Creating folder \"Wiki\Icons\Tango\"..."
    mkdir Tango
fi
cd Tango

# Tango - Dokument
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/accessories-text-editor.png -O accessories-text-editor.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/bookmark-new.png -O bookmark-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/calc.png -O calc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/contact-new.png -O contact-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-new.png -O document-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-open.png -O document-open.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-print.png -O document-print.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-properties.png -O document-properties.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-save-as.png -O document-save-as.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-save.png -O document-save.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-clear.png -O edit-clear.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-copy.png -O edit-copy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-cut.png -O edit-cut.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-delete.png -O edit-delete.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-find.png -O edit-find.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-paste.png -O edit-paste.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-select-all.png -O edit-select-all.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/file-manager.png -O file-manager.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder-new.png -O folder-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder.png -O folder.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder-remote.png -O folder-remote.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder-saved-search.png -O folder-saved-search.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/text-editor.png -O text-editor.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/user-home.png -O user-home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/video-display.png -O video-display.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/info.png -O info.png

# Tango - Dateityp
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/audio-x-generic.png -O audio-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/image-x-generic.png -O image-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/text-x-generic.png -O text-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/video-x-generic.png -O video-x-generic.png

# Tango - Navigation
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-bottom.png -O go-bottom.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-down.png -O go-down.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-first.png -O go-first.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-home.png -O go-home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-jump.png -O go-jump.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-last.png -O go-last.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-next.png -O go-next.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-previous.png -O go-previous.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-top.png -O go-top.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-up.png -O go-up.png

# Tango - Internet
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/internet-mail.png -O internet-mail.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/internet-news-reader.png -O internet-news-reader.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/internet-group-chat.png -O internet-group-chat.png

# Tango Netzwerk
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-error.png -O network-error.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-offline.png -O network-offline.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-transmit-receive.png -O network-transmit-receive.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-wired.png -O network-wired.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-wireless.png -O network-wireless.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-idle.png -O network-idle.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-receive.png -O network-receive.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-transmit.png -O network-transmit.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-wireless-encrypted.png -O network-wireless-encrypted.png

# Tango - Listen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/list-add.png -O list-add.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/list-remove.png -O list-remove.png

# Tango - Multimedia
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-eject.png -O media-eject.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-playback-start.png -O media-playback-start.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-record.png -O media-record.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-seek-forward.png -O media-seek-forward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-skip-forward.png -O media-skip-forward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-playback-pause.png -O media-playback-pause.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-playback-stop.png -O media-playback-stop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-seek-backward.png -O media-seek-backward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-skip-backward.png -O media-skip-backward.png

# Tango - System
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/process-stop.png -O process-stop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-lock-screen.png -O system-lock-screen.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-log-out.png -O system-log-out.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-search.png -O system-search.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-shutdown.png -O system-shutdown.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/user-desktop.png -O user-desktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/user-trash.png -O user-trash.png

# Tango - Ansichtsmodi
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/view-fullscreen.png -O view-fullscreen.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-best-fit.png -O zoom-best-fit.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-original.png -O zoom-original.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/view-refresh.png -O view-refresh.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-in.png -O zoom-in.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-out.png -O zoom-out.png

# Tango - Diverse
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/camera-photo.png -O camera-photo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/camera-video.png -O camera-video.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/computer.png -O computer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/drive-harddisk.png -O drive-harddisk.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/drive-optical.png -O drive-optical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/drive-removable-media.png -O drive-removable-media.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/input-gaming.png -O input-gaming.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/input-keyboard.png -O input-keyboard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/input-mouse.png -O input-mouse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-flash.png -O media-flash.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-floppy.png -O media-floppy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-optical.png -O media-optical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/multimedia-player.png -O multimedia-player.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/printer.png -O printer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/audio-card.png -O audio-card.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/audio-input-microphone.png -O audio-input-microphone.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/battery.png -O battery.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/office-calendar.png -O office-calendar.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/help-browser.png -O help-browser.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop.png -O preferences-desktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-locale.png -O preferences-desktop-locale.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-accessibility.png -O preferences-desktop-accessibility.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-assistive-technology.png -O preferences-desktop-assistive-technology.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-font.png -O preferences-desktop-font.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-keyboard-shortcuts.png -O preferences-desktop-keyboard-shortcuts.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-theme.png -O preferences-desktop-theme.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-wallpaper.png -O preferences-desktop-wallpaper.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/emblem-favorite.png -O emblem-favorite.png

# Tango - Dialoge
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/dialog-ok.png -O dialog-ok.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/dialog-cancel.png -O dialog-cancel.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/dialog-information.png -O dialog-information.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/dialog-warning.png -O dialog-warning.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/dialog-error.png -O dialog-error.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/X.png -O X.png


cd ..

if [ ! -d Oxygen ]
  then
    echo "Creating folder \"Wiki\Icons\Oxygen\"..."
    mkdir Oxygen
fi
cd Oxygen

# Oxygen - Dokument
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/accessories-text-editor.png -O accessories-text-editor.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-new.png -O document-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-print.png -O document-print.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-save.png -O document-save.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-copy.png -O edit-copy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-delete.png -O edit-delete.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-paste.png -O edit-paste.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/folder-new.png -O folder-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/folder-remote.png -O folder-remote.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-properties.png -O document-properties.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/fileclose.png -O fileclose.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/bookmark-new.png -O bookmark-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-open.png -O document-open.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-save-as.png -O document-save-as.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-clear.png -O edit-clear.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-cut.png -O edit-cut.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-find.png -O edit-find.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-select-all.png -O edit-select-all.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/folder.png -O folder.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-home.png -O user-home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/datashow.png -O datashow.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/contents.png -O contents.png

# Oxygen - Dateityp
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-x-generic.png -O audio-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/image-x-generic.png -O image-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/pdf.png -O pdf.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/text-x-generic.png -O text-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-x-generic.png -O video-x-generic.png

# Oxygen - Navigation
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-bottom.png -O go-bottom.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-first.png -O go-first.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-jump.png -O go-jump.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-next.png -O go-next.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-top.png -O go-top.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-down.png -O go-down.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-home.png -O go-home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-last.png -O go-last.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-previous.png -O go-previous.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-up.png -O go-up.png

# Oxygen - Internet
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/internet-mail.png -O internet-mail.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/internet-web-browser.png -O internet-web-browser.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/internet-telephony.png -O internet-telephony.png

# Oxygen - Netzwerk
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-wired.png -O network-wired.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-wireless.png -O network-wireless.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-connect.png -O network-connect.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-disconnect.png -O network-disconnect.png

# Oxygen - Listen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/list-add.png -O list-add.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/list-remove.png -O list-remove.png

# Oxygen - Multimedia
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-eject.png -O media-eject.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playback-start.png -O media-playback-start.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-record.png -O media-record.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-seek-forward.png -O media-seek-forward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-skip-forward.png -O media-skip-forward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playlist-repeat.png -O media-playlist-repeat.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playback-pause.png -O media-playback-pause.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playback-stop.png -O media-playback-stop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-seek-backward.png -O media-seek-backward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-skip-backward.png -O media-skip-backward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playlist-shuffle.png -O media-playlist-shuffle.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-media-equalizer.png -O view-media-equalizer.png

# Oxygen - System
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/process-stop.png -O process-stop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-search.png -O system-search.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-desktop.png -O user-desktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-restart.png -O system-restart.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/tools_report_bug.png -O tools_report_bug.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-log-out.png -O system-log-out.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-shutdown.png -O system-shutdown.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-trash.png -O user-trash.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system_users.png -O system_users.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences.png -O preferences.png

# Oxygen - Ansichtsmodi
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-fullscreen.png -O view-fullscreen.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-best-fit.png -O zoom-best-fit.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-original.png -O zoom-original.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-refresh.png -O view-refresh.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-in.png -O zoom-in.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-out.png -O zoom-out.png

# Oxygen - Hardware
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-card.png -O audio-card.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-input-line.png -O audio-input-line.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/camera-photo.png -O camera-photo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/computer.png -O computer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/cpu.png -O cpu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-optical.png -O drive-optical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-removable-media-usb-pendrive.png -O drive-removable-media-usb-pendrive.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-gaming.png -O input-gaming.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-mouse.png -O input-mouse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash-memory-stick.png -O media-flash-memory-stick.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash-sd-mmc.png -O media-flash-sd-mmc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-floppy.png -O media-floppy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-optical.png -O media-optical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-tape.png -O media-tape.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/multimedia-player-apple-ipod.png -O multimedia-player-apple-ipod.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/pda.png -O pda.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/tablet.png -O tablet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/printer.png -O printer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-display.png -O video-display.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-television.png -O video-television.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-headset.png -O audio-headset.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-input-microphone.png -O audio-input-microphone.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/camera-web.png -O camera-web.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/computer-laptop.png -O computer-laptop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-harddisk.png -O drive-harddisk.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-removable-media.png -O drive-removable-media.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-removable-media-usb.png -O drive-removable-media-usb.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-keyboard.png -O input-keyboard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-tablet.png -O input-tablet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash.png -O media-flash.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash-smart-media.png -O media-flash-smart-media.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-optical-audio.png -O media-optical-audio.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-optical-recordable.png -O media-optical-recordable.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/modem.png -O modem.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/multimedia-player.png -O multimedia-player.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/phone.png -O phone.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/smartphone.png -O smartphone.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/scanner.png -O scanner.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-projector.png -O video-projector.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/battery.png -O battery.png

# Oxygen - Einstellungen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-other.png -O preferences-other.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop.png -O preferences-desktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-contact-list.png -O preferences-contact-list.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-color.png -O preferences-desktop-color.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-default-applications.png -O preferences-desktop-default-applications.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-font.png -O preferences-desktop-font.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-icons.png -O preferences-desktop-icons.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-locale.png -O preferences-desktop-locale.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-notification.png -O preferences-desktop-notification.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-printer.png -O preferences-desktop-printer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-sound.png -O preferences-desktop-sound.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-theme.png -O preferences-desktop-theme.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-user.png -O preferences-desktop-user.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-kcalc-constants.png -O preferences-kcalc-constants.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-bluetooth.png -O preferences-system-bluetooth.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-network-sharing.png -O preferences-system-network-sharing.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-time.png -O preferences-system-time.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-personal.png -O preferences-desktop-personal.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-filetype-association.png -O preferences-desktop-filetype-association.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-identity.png -O user-identity.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-session-services.png -O preferences-system-session-services.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-windows.png -O preferences-system-windows.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-power-management.png -O preferences-system-power-management.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-login.png -O preferences-system-login.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-plugin.png -O preferences-plugin.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-wallpaper.png -O preferences-desktop-wallpaper.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-user-password.png -O preferences-desktop-user-password.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-text-to-speech.png -O preferences-desktop-text-to-speech.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-screensaver.png -O preferences-desktop-screensaver.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-peripherals.png -O preferences-desktop-peripherals.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-mouse.png -O preferences-desktop-mouse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-keyboard.png -O preferences-desktop-keyboard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-gaming.png -O preferences-desktop-gaming.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-display.png -O preferences-desktop-display.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-cryptography.png -O preferences-desktop-cryptography.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-accessibility.png -O preferences-desktop-accessibility.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-network.png -O preferences-system-network.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system.png -O preferences-system.png

# Oxygen - Anwendungen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/k3b.png -O k3b.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/konversation.png -O konversation.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/partitionmanager.png -O partitionmanager.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/kaffeine.png -O kaffeine.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/hwinfo.png -O hwinfo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/nepomuk.png -O nepomuk.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-activities.png -O preferences-activities.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/k3b_1.png -O k3b_1.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/kontact.png -O kontact.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/knotes.png -O knotes.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/digikam.png -O digikam.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/akonadi.png -O akonadi.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/konsole.png -O konsole.png

# Oxygen - Diverses
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/office-calendar.png -O office-calendar.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/X.png -O X.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/terminal.png -O terminal.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/kde.png -O kde.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/plasma.png -O plasma.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/security-high.png -O security-high.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/security-low.png -O security-low.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications-games.png -O applications-games.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-run.png -O system-run.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/face-smile.png -O face-smile.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-calendar-day.png -O view-calendar-day.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/help-browser.png -O help-browser.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/emblem-favorite.png -O emblem-favorite.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/utilities-file-archiver.png -O utilities-file-archiver.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications-internet.png -O applications-internet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications-other.png -O applications-other.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/security-medium.png -O security-medium.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/dialog-ok-apply.png -O dialog-ok-apply.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/object-locked.png -O object-locked.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-software-update.png -O system-software-update.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/get-hot-new-stuff.png -O get-hot-new-stuff.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications_engineering.png -O applications_engineering.png


cd ..

if [ ! -d Breeze ]
  then
    echo "Creating folder \"Wiki\Icons\Breeze\"..."
    mkdir Breeze
fi
cd Breeze

# Breeze - Dokument
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/bookmark-new.png -O bookmark-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/document-new.png -O document-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/document-open.png -O document-open.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/document-print.png -O document-print.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/document-save-as.png -O document-save-as.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/document-save.png -O document-save.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/document-properties.png -O document-properties.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-clear.png -O edit-clear.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-copy.png -O edit-copy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-cut.png -O edit-cut.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-delete.png -O edit-delete.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-find.png -O edit-find.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-paste.png -O edit-paste.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/edit-select-all.png -O edit-select-all.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/folder-new.png -O folder-new.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/view-calendar-day.png -O view-calendar-day.png

# Breeze - Dateityp
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/audio-x-generic.png -O audio-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/image-x-generic.png -O image-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/pdf.png -O pdf.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/text-x-generic.png -O text-x-generic.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/video-x-generic.png -O video-x-generic.png

# Breeze - Navigation
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-bottom.png -O go-bottom.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-down.png -O go-down.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-first.png -O go-first.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-home.png -O go-home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-jump.png -O go-jump.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-last.png -O go-last.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-next.png -O go-next.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-previous.png -O go-previous.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-top.png -O go-top.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/go-up.png -O go-up.png

# Breeze - Internet
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/internet-mail.png -O internet-mail.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/internet-telephony.png -O internet-telephony.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/internet-web-browser.png -O internet-web-browser.png

# Breeze - Netzwerk
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/network-wired.png -O network-wired.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/network-wireless.png -O network-wireless.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/network-connect.png -O network-connect.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/network-disconnect.png -O network-disconnect.png

# Breeze - Listen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/list-add.png -O list-add.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/list-remove.png -O list-remove.png

# Breeze - Multimedia
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-eject.png -O media-eject.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-playback-pause.png -O media-playback-pause.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-playback-start.png -O media-playback-start.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-playback-stop.png -O media-playback-stop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-record.png -O media-record.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-seek-backward.png -O media-seek-backward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-seek-forward.png -O media-seek-forward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-skip-backward.png -O media-skip-backward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-skip-forward.png -O media-skip-forward.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-playlist-shuffle.png -O media-playlist-shuffle.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-playlist-repeat.png -O media-playlist-repeat.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/view-media-equalizer.png -O view-media-equalizer.png

# Breeze - System
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/folder.png -O folder.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/folder-remote.png -O folder-remote.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/process-stop.png -O process-stop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/system-log-out.png -O system-log-out.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/system-run.png -O system-run.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/system-search.png -O system-search.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/system-shutdown.png -O system-shutdown.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/user-desktop.png -O user-desktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/user-home.png -O user-home.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/user-trash.png -O user-trash.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/system-users.png -O system-users.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/tools-report-bug.png -O tools-report-bug.png

# Breeze - Anichtmodi
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/view-fullscreen.png -O view-fullscreen.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/view-refresh.png -O view-refresh.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/zoom-best-fit.png -O zoom-best-fit.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/zoom-in.png -O zoom-in.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/zoom-original.png -O zoom-original.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/zoom-out.png -O zoom-out.png

# Breeze - Hardware
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/audio-card.png -O audio-card.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/audio-headset.png -O audio-headset.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/camera-photo.png -O camera-photo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/camera-web.png -O camera-web.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/computer.png -O computer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/computer-laptop.png -O computer-laptop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/cpu.png -O cpu.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/drive-harddisk.png -O drive-harddisk.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/drive-removable-media.png -O drive-removable-media.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/input-gaming.png -O input-gaming.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/input-keyboard.png -O input-keyboard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/input-mouse.png -O input-mouse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/input-tablet.png -O input-tablet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-flash-memory-stick.png -O media-flash-memory-stick.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-flash-sd-mmc.png -O media-flash-sd-mmc.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-floppy.png -O media-floppy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-optical-audio.png -O media-optical-audio.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-optical.png -O media-optical.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/media-optical-recordable.png -O media-optical-recordable.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/modem.png -O modem.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/multimedia-player.png -O multimedia-player.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/printer.png -O printer.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/scanner.png -O scanner.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/smartphone.png -O smartphone.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/tablet.png -O tablet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/video-display.png -O video-display.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/video-television.png -O video-television.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/battery.png -O battery.png

# Breeze - Einstellungen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-activities.png -O preferences-activities.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop.png -O preferences-desktop.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-accessibility.png -O preferences-desktop-accessibility.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-color.png -O preferences-desktop-color.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-cryptography.png -O preferences-desktop-cryptography.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-default-applications.png -O preferences-desktop-default-applications.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-display.png -O preferences-desktop-display.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-filetype-association.png -O preferences-desktop-filetype-association.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-font.png -O preferences-desktop-font.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-gaming.png -O preferences-desktop-gaming.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-icons.png -O preferences-desktop-icons.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-keyboard.png -O preferences-desktop-keyboard.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-locale.png -O preferences-desktop-locale.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-mouse.png -O preferences-desktop-mouse.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-notification.png -O preferences-desktop-notification.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-peripherals.png -O preferences-desktop-peripherals.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-screensaver.png -O preferences-desktop-screensaver.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-sound.png -O preferences-desktop-sound.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-text-to-speech.png -O preferences-desktop-text-to-speech.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-theme.png -O preferences-desktop-theme.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-user-password.png -O preferences-desktop-user-password.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-user.png -O preferences-desktop-user.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-desktop-wallpaper.png -O preferences-desktop-wallpaper.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-bluetooth.png -O preferences-system-bluetooth.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-other.png -O preferences-other.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system.png -O preferences-system.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-login.png -O preferences-system-login.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-network-sharing.png -O preferences-system-network-sharing.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-power-management.png -O preferences-system-power-management.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-time.png -O preferences-system-time.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-windows.png -O preferences-system-windows.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/preferences-system-session-services.png -O preferences-system-session-services.png

# Breeze - Anwendungen
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/accessories-text-editor.png -O accessories-text-editor.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/akregator.png -O akregator.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/amarok.png -O amarok.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/applications-internet.png -O applications-internet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/applications-games.png -O applications-games.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/applications-other.png -O applications-other.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/baloo.png -O baloo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/digikam.png -O digikam.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/hwinfo.png -O hwinfo.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/k3b.png -O k3b.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/konversation.png -O konversation.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/kontact.png -O kontact.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/office-calendar.png -O office-calendar.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/partitionmanager.png -O partitionmanager.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/system-software-update.png -O system-software-update.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/terminal.png -O terminal.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/utilities-file-archiver.png -O utilities-file-archiver.png

# Breeze - Embleme
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-error.png -O emblem-error.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-information.png -O emblem-information.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-success.png -O emblem-success.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-warning.png -O emblem-warning.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-favorite.png -O emblem-favorite.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-locked.png -O emblem-locked.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-symbolic-link.png -O emblem-symbolic-link.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/emblem-unlocked.png -O emblem-unlocked.png

# Breeze - Diverses
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/dialog-ok-apply.png -O dialog-ok-apply.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/face-smile.png -O face-smile.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/get-hot-new-stuff.png -O get-hot-new-stuff.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/help-browser.png -O help-browser.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/kde.png -O kde.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/plasma.png -O plasma.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/security-high.png -O security-high.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/security-medium.png -O security-medium.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/security-low.png -O security-low.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Breeze/user-identity.png -O user-identity.png


cd ..

if [ ! -d Portal ]
  then
    echo "Creating folder \"Wiki\Icons\Portal\"..."
    mkdir Portal
fi
cd Portal

wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/portal.png -O portal.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/ikhaya.png -O ikhaya.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/ubuntuusers.png -O ubuntuusers.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/community.png -O community.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-preferences.png -O usercp-preferences.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-profile.png -O usercp-profile.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-wikipage.png -O usercp-wikipage.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/anchor.png -O anchor.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/download-attachment.png -O download-attachment.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/mark.png -O mark.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/picture.png -O picture.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/topic-solved-locked.png -O topic-solved-locked.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/forum.png -O forum.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/planet.png -O planet.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/wiki.png -O wiki.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/wochenrueckblick.png -O wochenrueckblick.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-password.png -O usercp-password.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-subscriptions.png -O usercp-subscriptions.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/code.png -O code.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/download.png -O download.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/userlink.png -O userlink.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/wikilink.png -O wikilink.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/expand.png -O expand.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/ubuntu-community.png -O ubuntu-community.png

cd ..
cd ..

if [ ! -d Vorlagen ]
  then
    echo "Creating folder \"Wiki\Vorlagen\"..."
    mkdir Vorlagen
fi
cd Vorlagen

if [ ! -d StatusIcon ]
  then
    echo "Creating folder \"Wiki\Vorlagen\StatusIcon\"..."
    mkdir StatusIcon
fi
cd StatusIcon

wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/ja.png -O ja.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/alpha.png -O alpha.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/bedingt.png -O bedingt.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/plugin.png -O plugin.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/buggy.png -O buggy.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/nein.png -O nein.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/unbekannt.png -O unbekannt.png
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/StatusIcon/manuell.png -O manuell.png

cd ..
if [ ! -d PPA ]
  then
    echo "Creating folder \"Wiki\Vorlagen\PPA\"..."
    mkdir PPA
fi
cd PPA
wget -nv https://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/PPA/ppa.png -O ppa.png

cd ${PROJECT}

echo "DOWNLOAD FINISHED"
sleep 2
