#!/bin/bash
# GetIWLs from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

PROJECT="${1}"

if [ "${PROJECT}" == "" ]
  then
    echo "USAGE: ./`basename $0` [STYLES FOLDER]"
    exit
fi

if [ ! -d ${PROJECT} ]
  then
    echo "Creating styles main folder..."
    mkdir -p ${PROJECT}
fi
cd ${PROJECT}

if [ ! -d styles ]
  then
    echo "Creating folder \"styles\"..."
    mkdir styles
fi
cd styles

echo "Downloading css files..."
rm main.css
rm markup.css
rm wiki.css
rm highlight.css

wget -nv https://static-cdn.ubuntu-de.org/style/main.css
wget -nv https://static-cdn.ubuntu-de.org/style/markup.css
wget -nv https://static-cdn.ubuntu-de.org/style/wiki.css
wget -nv https://static-cdn.ubuntu-de.org/style/highlight.css

echo "Replace static paths..."
## Paths
_r1="//media-cdn.ubuntu-de.org/wiki/attachments/[0-9][0-9]/[0-9][0-9]"
_r2="../img/interwiki"
## Escape path for sed using bash find and replace
_r1="${_r1//\//\\/}"
_r2="${_r2//\//\\/}"
## Replace paths
sed -e "s/${_r1}/${_r2}/g" -i markup.css

cd ..

if [ ! -d font ]
  then
    echo "Creating folder \"font\"..."
    mkdir font
fi
cd font

if [ ! -d Liberation_webkit_macroman ]
  then
    mkdir Liberation_webkit_macroman
fi
cd Liberation_webkit_macroman

if [ ! -d Sans ]
  then
    mkdir Sans
fi
cd Sans

if [ ! -d Regular ]
  then
    mkdir Regular
fi
cd Regular
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Regular/LiberationSans-Regular-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Regular/LiberationSans-Regular-webfont.ttf

cd ..
if [ ! -d Italic ]
  then
    mkdir Italic
fi
cd Italic
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Italic/LiberationSans-Italic-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Italic/LiberationSans-Italic-webfont.ttf

cd ..
if [ ! -d Bold ]
  then
    mkdir Bold
fi
cd Bold
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Bold/LiberationSans-Bold-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/Bold/LiberationSans-Bold-webfont.ttf

cd ..
if [ ! -d BoldItalic ]
  then
    mkdir BoldItalic
fi
cd BoldItalic
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/BoldItalic/LiberationSans-BoldItalic-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Sans/BoldItalic/LiberationSans-BoldItalic-webfont.ttf

cd ..
cd ..
if [ ! -d Mono ]
  then
    mkdir Mono
fi
cd Mono
if [ ! -d Regular ]
  then
    mkdir Regular
fi
cd Regular
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Mono/Regular/LiberationMono-Regular-webfont.woff
wget -nv https://static-cdn.ubuntu-de.org/font/Liberation_webkit_macroman/Mono/Regular/LiberationMono-Regular-webfont.ttf

cd ..
cd ..
cd ..
if [ ! -d uude-font-0.83 ]
  then
    mkdir uude-font-0.83
fi
cd uude-font-0.83
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-bold.woff2
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-bold.woff
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-bold.ttf
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-light.woff2
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-light.woff
wget -nv https://static-cdn.ubuntu-de.org/font/uude-font-0.83/ubuntu_derivative_uude-light.ttf

cd ..

wget -nv https://static-cdn.ubuntu-de.org/img/interwiki/search.png -O search.png
wget -nv https://media-cdn.ubuntu-de.org/wiki/attachments/17/43/ppa.png -O ppa.png

echo "IWL DOWNLOAD FINISHED"
