#!/bin/bash
# GetInyokaStyles from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

baseurl="https://wiki.ubuntuusers.de/"

if [ ! -d style ]
  then
    echo "Creating folder \"style\" ..."
    mkdir style
fi
cd style


echo "Trying to find CSS files ..."
maincss=$(wget -qO- $baseurl | grep -Eo '[0-9a-zA-Z._-]*/style/main\.css\?v=[0-9a-zA-Z.]*')
if [ "${maincss}" == "" ]
  then
    echo "ERROR: Could not find main.css"
    exit
fi
echo "Found main.css: $maincss"
rm main.css
wget -nv https://$maincss -O main.css

wikicss=$(wget -qO- $baseurl | grep -Eo '[0-9a-zA-Z._-]*/style/wiki\.css\?v=[0-9a-zA-Z.]*')
if [ "${wikicss}" == "" ]
  then
    echo "ERROR: Could not find wiki.css"
    exit
fi
echo "Found wiki.css: $wikicss"
rm wiki.css
wget -nv https://$wikicss -O wiki.css

highlightcss=$(wget -qO- $baseurl | grep -Eo '[0-9a-zA-Z._-]*/style/highlight\.css\?v=[0-9a-zA-Z.]*')
if [ "${highlightcss}" == "" ]
  then
    echo "ERROR: Could not find highlight.css"
    exit
fi
echo "Found highlight.css: $highlightcss"
rm highlight.css
wget -nv https://$highlightcss -O highlight.css

markupcss=$(wget -qO- $baseurl | grep -Eo '[0-9a-zA-Z._-]*/style/markup\.css\?v=[0-9a-zA-Z.]*')
if [ "${markupcss}" == "" ]
  then
    echo "ERROR: Could not find markup.css"
    exit
fi
echo "Found markup.css: $markupcss"
rm markup.css
wget -nv https://$markupcss -O markup.css

url=${markupcss%"markup.css"}
echo "URL: $markupcss"

cd ..


if [ ! -d img ]
  then
    echo "Creating folder \"img\" ..."
    mkdir img
fi
cd img

## Remove everything after last /
url=${markupcss%/*}
url="https://${url}/"

echo "Downloading images ..."
wget -nv "${url}../img/favicon.ico" -O favicon.ico
wget -nv "${url}../img/wiki.svg" -O wiki.svg


if [ ! -d icons ]
  then
    echo "Creating folder \"icons\" ..."
    mkdir icons
fi
cd icons
wget -nv "${url}../img/icons/ikhaya.svg" -O ikhaya.svg
wget -nv "${url}../img/icons/portal.svg" -O portal.svg
wget -nv "${url}../img/icons/search.svg" -O search.svg
wget -nv "${url}../img/icons/forum.svg" -O forum.svg
wget -nv "${url}../img/icons/planet.svg" -O planet.svg
wget -nv "${url}../img/icons/actions.svg" -O actions.svg
cd ..

if [ ! -d interwiki ]
  then
    echo "Creating folder \"interwiki\" ..."
    mkdir interwiki
fi
cd interwiki
wget -nv "${url}../img/interwiki/search.png" -O search.png
wget -nv "${url}../img/interwiki/team.png" -O team.png
wget -nv "${url}../img/interwiki/user.png" -O user.png
cd ..

if [ ! -d smiley_icons ]
  then
    echo "Creating folder \"smiley_icons\" ..."
    mkdir smiley_icons
fi
cd smiley_icons
wget -nv "${url}../img/smiley_icons/frog-xmas.png" -O frog-xmas.png
wget -nv "${url}../img/smiley_icons/tux.png" -O tux.png
wget -nv "${url}../img/smiley_icons/ubuntu.png" -O ubuntu.png
wget -nv "${url}../img/smiley_icons/ubuntugnome.png" -O ubuntugnome.png
wget -nv "${url}../img/smiley_icons/kubuntu.png" -O kubuntu.png
wget -nv "${url}../img/smiley_icons/lubuntu.png" -O lubuntu.png
wget -nv "${url}../img/smiley_icons/ubuntumate.png" -O ubuntumate.png
wget -nv "${url}../img/smiley_icons/mythbuntu.png" -O mythbuntu.png
wget -nv "${url}../img/smiley_icons/ubuntutouch.png" -O ubuntutouch.png
wget -nv "${url}../img/smiley_icons/xubuntu.png" -O xubuntu.png
cd ..
cd ..

if [ ! -d font ]
  then
    echo "Creating folder \"font\" ..."
    mkdir font
fi
rm ./font/*
cd font

echo "Downloading fonts ..."
## Find all fonts in main.css
fonturls=($(grep -Eo '../font/[0-9a-zA-Z/._-]*\.(woff2?|ttf)' ../style/main.css))
for i in "${fonturls[@]}"; do wget -nv "${url}${i}"; done
cd ..

echo "Removing font subfolders from main.css"
for i in "${fonturls[@]}"
do
  _r1=${i}
  _r2="../font/"${i##*/}
  #echo "R1: ${_r1}"
  #echo "R2: ${_r2}"
  ## Escape path for sed using bash find and replace
  _r1="${_r1//\//\\/}"
  _r2="${_r2//\//\\/}"
  sed -e "s/${_r1}/${_r2}/g" -i ./style/main.css
done

echo "DOWNLOAD OF STYLE FILES FINISHED"
