version: 0.27.3-{build}
branches:
  only:
  - main
environment:
  matrix:
  - BUILD: x86
    QTDIR: C:\Qt\5.15\msvc2019
    VCPKG_DIR: C:\Tools\vcpkg
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VSVER: 2019
  - BUILD: x64
    QTDIR: C:\Qt\6.5\msvc2022_64
    VCPKG_DIR: C:\Tools\vcpkg
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    VSVER: 2022
install:
- ps: (Get-Content plugins/plugins.pro).replace("spellchecker-hunspell ", "spellchecker-nuspell ") | Set-Content plugins/plugins.pro
cache: '%VCPKG_DIR%\installed\ -> vcpkg.json'
build_script:
- cmd: >-
    %VCPKG_DIR%\vcpkg.exe version

    cd "C:\Tools\vcpkg"

    git pull

    .\bootstrap-vcpkg.bat

    cd %APPVEYOR_BUILD_FOLDER%

    %VCPKG_DIR%\vcpkg.exe version

    echo set(VCPKG_BUILD_TYPE release) >> %VCPKG_DIR%\triplets\%BUILD%-windows.cmake

    type %VCPKG_DIR%\triplets\%BUILD%-windows.cmake

    %VCPKG_DIR%\vcpkg.exe install --triplet %BUILD%-windows "--x-install-root=%VCPKG_DIR%\installed"

    %VCPKG_DIR%\vcpkg.exe list

    tree /f /a %VCPKG_DIR%\installed\%BUILD%-windows\lib

    tree /f /a %VCPKG_DIR%\installed\%BUILD%-windows\bin

    tree /f /a %VCPKG_DIR%\installed\%BUILD%-windows\include

    git clone -b packaging --single-branch https://github.com/inyokaproject/inyokaedit.git packaging

    git clone -b community --single-branch https://github.com/inyokaproject/inyokaedit.git community

    set PATH=%QTDIR%\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio\%VSVER%\Community\VC\Auxiliary\Build\vcvarsall.bat" %BUILD%

    qmake inyokaedit.pro

    lrelease application\application.pro

    lrelease plugins\highlighter\highlighter.pro

    lrelease plugins\hotkey\hotkey.pro

    lrelease plugins\spellchecker-nuspell\spellchecker-nuspell.pro

    lrelease plugins\uu_knowledgebox\uu_knowledgebox.pro

    lrelease plugins\uu_tabletemplate\uu_tabletemplate.pro

    nmake

    mkdir InyokaEdit\plugins

    mkdir InyokaEdit\community

    copy release\..\InyokaEdit.exe InyokaEdit\InyokaEdit.exe

    windeployqt --release --no-translations --no-angle --no-opengl-sw InyokaEdit\InyokaEdit.exe

    copy COPYING InyokaEdit\

    copy application\3rdparty\miniz\LICENSE InyokaEdit\Miniz_License.txt

    copy packaging\Windows\ICU_License.txt InyokaEdit\

    copy packaging\Windows\Nuspell_License.txt InyokaEdit\

    copy packaging\Windows\OpenSSL_%BUILD%\* InyokaEdit\

    xcopy /y /d %VCPKG_DIR%\installed\%BUILD%-windows\bin\*.dll InyokaEdit\

    xcopy /i /e /s packaging\Windows\dicts InyokaEdit\dicts\

    copy release\..\plugins\*.dll InyokaEdit\plugins\

    chcp 65001 && xcopy /i /e /s community\* InyokaEdit\community\

    rmdir /S /Q InyokaEdit\iconengines

    rmdir /S /Q InyokaEdit\imageformats

    rmdir /S /Q InyokaEdit\position

    7z a InyokaEdit-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip .\InyokaEdit\

    copy packaging\Windows\inyokaedit.nsi inyokaedit.nsi

    copy packaging\Windows\inyokaedit.ico inyokaedit.ico

    makensis inyokaedit.nsi

    ren InyokaEdit_Installer.exe InyokaEdit-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe
artifacts:
- path: InyokaEdit-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip
- path: InyokaEdit-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe
