#!/bin/bash
# GetInyokaStyles from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

PROJECT="${1}"

if [ ! -d ${PROJECT} ]
  then
    echo "Creating main folder..."
    mkdir -p ${PROJECT}
fi

cd ${PROJECT}

if [ ! -d styles ]
  then
    echo "Creating folder \"styles\"..."
    mkdir styles
fi

cd styles

echo "Downloading css files..."
rm markup.css
rm markup2.css
rm wiki.css
rm main-sprite.css
wget -nv http://static.cdn.ubuntu-de.org/style/markup.css
mv markup.css markup2.css
wget -nv http://static.cdn.ubuntu-de.org/style/wiki.css
wget -nv http://static.cdn.ubuntu-de.org/style/main-sprite.css
wget -nv http://ubuntuusers.de/markup.css

echo "Replace static paths..."
## Paths
_r1="http://static.cdn.ubuntu-de.org"
_r2="http://media.cdn.ubuntu-de.org/wiki/attachments/[0-9][0-9]/[0-9][0-9]"
_r3="../img/interwiki"
## Escape path for sed using bash find and replace
_r1="${_r1//\//\\/}"
_r2="${_r2//\//\\/}"
_r3="${_r3//\//\\/}"
## Replace paths
sed -e "s/${_r1}/../g" -i markup.css
sed -e "s/${_r2}/${_r3}/g" -i markup.css

cd ..

if [ ! -d img ]
  then
    echo "Creating folder \"img\"..."
    mkdir img
fi

cd img

echo "Downloading images..."
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/anchor.png -O anchor.png

if [ ! -d interwiki ]
  then
    echo "Creating folder \"interwiki\"..."
    mkdir interwiki
fi

cd interwiki

wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/archwiki.png -O archwiki.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/askubuntu.png -O askubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/bitbucket.png -O bitbucket.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/brainstorm.png -O brainstorm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/bug.png -O bug.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonical.png -O canonical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonicalblog.png -O canonicalblog.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonicalvoices.png -O canonicalvoices.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debian.png -O debian.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debianbug.png -O debianbug.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debian_de.png -O debian_de.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/desura.png -O desura.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/diaspora.png -O diaspora.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/dropbox.png -O dropbox.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ean.png -O ean.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/edubuntu.png -O edubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/fb.png -O fb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freecode.png -O freecode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freenode.png -O freenode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freshmeat.png -O freshmeat.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gameolith.png -O gameolith.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/getdeb.png -O getdeb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/github.png -O github.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnome.png -O gnome.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/googlecode.png -O googlecode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/googlevideo.png -O googlevideo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gplus.png -O gplus.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/holarse.png -O holarse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/humble.png -O humble.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/iawm.png -O iawm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/identica.png -O identica.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/isbn.png -O isbn.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu.png -O kubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu-de.png -O kubuntu-de.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu_doc.png -O kubuntu_doc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lastfm.png -O lastfm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/launchpad.png -O launchpad.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lpcode.png -O lpcode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/liflg.jpg -O liflg.jpg
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/linuxgaming.png -O linuxgaming.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lpuser.png -O lpuser.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lubuntu.png -O lubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/man.png -O man.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ml.png -O ml.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/moby.png -O moby.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/moddb.png -O moddb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/mythbuntu.png -O mythbuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/omgubuntu.png -O omgubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/osm.png -O osm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/packages.png -O packages.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/playdeb.png -O playdeb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/sourceforge.png -O sourceforge.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/sourceforge2.png -O sourceforge2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/steam.png -O steam.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/team.png -O team.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ticket.png -O ticket.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/twitter.png -O twitter.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu.png -O ubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntuapps.png -O ubuntuapps.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_forum.png -O uf_forum.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_member.png -O uf_member.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_thread.png -O uf_thread.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntuone.png -O ubuntuone.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntustudio.png -O ubuntustudio.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu_doc.png -O ubuntu_doc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu_fr.png -O ubuntu_fr.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/user.png -O user.png
cp user.png user-xmas.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/vimeo.png -O vimeo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikibooks.png -O wikibooks.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikimedia.png -O wikimedia.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikipedia.png -O wikipedia.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikipedia_en.png -O wikipedia_en.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wordpress.png -O wordpress.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/xfcedocs.png -O xfcedocs.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/xubuntu.png -O xubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/youtube.png -O youtube.png

wget -nv http://static.cdn.ubuntu-de.org/img/interwiki/search.png -O search.png
wget -nv http://media.cdn.ubuntu-de.org/wiki/attachments/17/43/ppa.png -O ppa.png
cd ..

if [ ! -d flags ]
  then
    echo "Creating folder \"wiki\"..."
    mkdir wiki
fi
cd wiki

wget -nv http://static.cdn.ubuntu-de.org/img/wiki/toc.png -O toc.png
wget -nv http://media.cdn.ubuntu-de.org/wiki/attachments/42/17/button.png -O button.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/mouse_left.png -O mouse_left.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/mouse_midd.png -O mouse_midd.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Vorlagen/Tasten/mouse_right.png -O mouse_right.png
wget -nv http://static.cdn.ubuntu-de.org/img/wiki/heading.png -O heading.png
cd ..

if [ ! -d flags ]
  then
    echo "Creating folder \"flags\"..."
    mkdir flags
fi

cd flags

wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ar.png -O ar.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/at.png -O at.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/au.png -O au.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/be.png -O be.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ca.png -O ca.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cat.png -O cat.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ch.png -O ch.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cl.png -O cl.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/cz.png -O cz.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/da.png -O da.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/de.png -O de.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/gb.png -O gb.png
cp gb.png en.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/eo.png -O eo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/es.png -O es.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/eu.png -O eu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/fi.png -O fi.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/fr.png -O fr.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/gr.png -O gr.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/hr.png -O hr.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/hu.png -O hu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/id.png -O id.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ie.png -O ie.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/il.png -O il.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ir.png -O ir.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/it.png -O it.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ja.png -O ja.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ko.png -O ko.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/lv.png -O lv.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/nl.png -O nl.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/nw.png -O nw.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/pl.png -O pl.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/pt.png -O pt.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ro.png -O ro.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/rs.png -O rs.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/ru.png -O ru.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/sk.png -O sk.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/sv.png -O sv.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/tr.png -O tr.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/us.png -O us.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/FlaggenMap/zh.png -O zh.png

wget -nv http://media.cdn.ubuntu-de.org/wiki/attachments/08/15/overview.png -O overview.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/download.png -O dl.png

cd ..
cd ..

if [ ! -d Wiki ]
  then
    echo "Creating folder \"Wiki\"..."
    mkdir Wiki
fi

cd Wiki

if [ ! -d Icons ]
  then
    echo "Creating folder \"Wiki\Icons\"..."
    mkdir Icons
fi

cd Icons

# Linux
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu.png -O ubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/kubuntu.png -O kubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/edubuntu.png -O edubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gobuntu.png -O gobuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/lubuntu.png -O lubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu-community.png -O ubuntu-community.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntu64.png -O ubuntu64.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/xubuntu.png -O xubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ubuntustudio.png -O ubuntustudio.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/kxubuntu.png -O kxubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/brainstorm.png -O brainstorm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome.png -O gnome.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnu.png -O gnu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/debian.png -O debian.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/redhat.png -O redhat.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tux.png -O tux.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/suse.png -O suse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/arch.png -O arch.png

# Programme
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/calc.png -O calc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/dtp.png -O dtp.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/file-manager.png -O file-manager.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/synaptic.png -O synaptic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/text-editor.png -O text-editor.png

# Hardware
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/2monitors.png -O 2monitors.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/camera.png -O camera.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/computer.png -O computer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/floppy.png -O floppy.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/games.png -O games.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hd.png -O hd.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hd-linux.png -O hd-linux.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hd-windows.png -O hd-windows.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ipod-mini-blue.png -O ipod-mini-blue.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ipod-photos.png -O ipod-photos.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/joystick.png -O joystick.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mouse.png -O mouse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mouse2.png -O mouse2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/notebook.png -O notebook.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/pci.png -O pci.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/portablemp3.png -O portablemp3.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/printer.png -O printer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/printer2.png -O printer2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/scanner.png -O scanner.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tv.png -O tv.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/tv2.png -O tv2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/usb.png -O usb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/CPU.png -O CPU.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/bluetooth.png -O bluetooth.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/keyboard.png -O keyboard.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/mouse3.png -O mouse3.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/backup.png -O backup.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/download_manager.png -O download_manager.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/harddrive.png -O harddrive.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/removable-usb.png -O removable-usb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/network_local.png -O network_local.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/networksettings.png -O networksettings.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/removable.png -O removable.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/removable-1394.png -O removable-1394.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/SSD.png -O SSD.png

# System
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/access.png -O access.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/advancedsettings.png -O advancedsettings.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/button_cancel.png -O button_cancel.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/config.png -O config.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/develop.png -O develop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/dvd.png -O dvd.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/globe.png -O globe.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome-cd.png -O gnome-cd.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome-reclevel.png -O gnome-reclevel.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/gnome-warning.png -O gnome-warning.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/help.png -O help.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/home.png -O home.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/internet.png -O internet.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/konsole2.png -O konsole2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/multimedia.png -O multimedia.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/optical.png -O optical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/search2.png -O search2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/secure_non.png -O secure_non.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/security.png -O security.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/settings.png -O settings.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/sound.png -O sound.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/soundcontrol.png -O soundcontrol.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/terminal.png -O terminal.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/volume.png -O volume.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/trash.png -O trash.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/service.png -O service.png

# Sonstige
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/ati.png -O ati.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/background.png -O background.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/blackbox.png -O blackbox.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/box.png -O box.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/burning.png -O burning.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/community-help.png -O community-help.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/contact.png -O contact.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/date.png -O date.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/email.png -O email.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/hint.png -O hint.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/improvements.png -O improvements.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/looknfeel.png -O looknfeel.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/movies.png -O movies.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/package.png -O package.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/panel.png -O panel.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/pencil.png -O pencil.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/rss.png -O rss.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/save_all.png -O save_all.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/time.png -O time.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/wiki.png -O wiki.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/unknown.png -O unknown.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/openstreetmap.png -O openstreetmap.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/users.png -O users.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/windows_users.png -O windows_users.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/window.png -O window.png


if [ ! -d Protokolle ]
  then
    echo "Creating folder \"Wiki\Icons\Protokolle\"..."
    mkdir Protokolle
fi

cd Protokolle

# Protokolle
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/aim.png -O aim.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/bonjour.png -O bonjour.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/facebook.png -O facebook.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/gadu-gadu.png -O gadu-gadu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/google.png -O google.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/icq.png -O icq.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/irc.png -O irc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/msn.png -O msn.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/mrim.png -O mrim.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/mxit.png -O mxit.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/myspace.png -O myspace.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/novell.png -O novell.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/qq.png -O qq.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/sametime.png -O sametime.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/silc.png -O silc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/simple.png -O simple.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/vkontakte.png -O vkontakte.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/xmpp.png -O xmpp.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/yahoo.png -O yahoo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Protokolle/zephyr.png -O zephyr.png

cd ..

if [ ! -d Tango ]
  then
    echo "Creating folder \"Wiki\Icons\Tango\"..."
    mkdir Tango
fi

cd Tango

# Tango - Dokument
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/accessories-text-editor.png -O accessories-text-editor.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-new.png -O document-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-print.png -O document-print.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-save.png -O document-save.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-copy.png -O edit-copy.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-delete.png -O edit-delete.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-paste.png -O edit-paste.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder-new.png -O folder-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder-remote.png -O folder-remote.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/user-home.png -O user-home.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/contact-new.png -O contact-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/bookmark-new.png -O bookmark-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-open.png -O document-open.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-save-as.png -O document-save-as.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-clear.png -O edit-clear.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-cut.png -O edit-cut.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-find.png -O edit-find.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/edit-select-all.png -O edit-select-all.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder.png -O folder.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/folder-saved-search.png -O folder-saved-search.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/document-properties.png -O document-properties.png

# Tango - Dateityp
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/audio-x-generic.png -O audio-x-generic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/image-x-generic.png -O image-x-generic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/text-x-generic.png -O text-x-generic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/video-x-generic.png -O video-x-generic.png

# Tango - Navigation
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-bottom.png -O go-bottom.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-first.png -O go-first.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-jump.png -O go-jump.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-next.png -O go-next.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-top.png -O go-top.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-down.png -O go-down.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-home.png -O go-home.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-last.png -O go-last.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-previous.png -O go-previous.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/go-up.png -O go-up.png

# Tango - Internet
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/internet-mail.png -O internet-mail.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/internet-news-reader.png -O internet-news-reader.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/internet-group-chat.png -O internet-group-chat.png

# Tango Netzwerk
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-error.png -O network-error.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-offline.png -O network-offline.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-transmit-receive.png -O network-transmit-receive.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-wired.png -O network-wired.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-wireless.png -O network-wireless.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-idle.png -O network-idle.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-receive.png -O network-receive.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-transmit.png -O network-transmit.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/network-wireless-encrypted.png -O network-wireless-encrypted.png

# Tango - Listen
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/list-add.png -O list-add.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/list-remove.png -O list-remove.png

# Tango - Multimedia
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-eject.png -O media-eject.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-playback-start.png -O media-playback-start.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-record.png -O media-record.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-seek-forward.png -O media-seek-forward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-skip-forward.png -O media-skip-forward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-playback-pause.png -O media-playback-pause.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-playback-stop.png -O media-playback-stop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-seek-backward.png -O media-seek-backward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-skip-backward.png -O media-skip-backward.png

# Tango - System
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/process-stop.png -O process-stop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-search.png -O system-search.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/user-desktop.png -O user-desktop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-log-out.png -O system-log-out.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/system-shutdown.png -O system-shutdown.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/user-trash.png -O user-trash.png

# Tango - Ansichtsmodi
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/view-fullscreen.png -O view-fullscreen.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-best-fit.png -O zoom-best-fit.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-original.png -O zoom-original.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/view-refresh.png -O view-refresh.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-in.png -O zoom-in.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/zoom-out.png -O zoom-out.png

# Tango - Diverse
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/camera-photo.png -O camera-photo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/computer.png -O computer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/drive-optical.png -O drive-optical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/input-gaming.png -O input-gaming.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/input-mouse.png -O input-mouse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-floppy.png -O media-floppy.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/multimedia-player.png -O multimedia-player.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/audio-card.png -O audio-card.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/battery.png -O battery.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/help-browser.png -O help-browser.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-locale.png -O preferences-desktop-locale.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-assistive-technology.png -O preferences-desktop-assistive-technology.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-keyboard-shortcuts.png -O preferences-desktop-keyboard-shortcuts.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-wallpaper.png -O preferences-desktop-wallpaper.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/emblem-favorite.png -O emblem-favorite.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/camera-video.png -O camera-video.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/drive-harddisk.png -O drive-harddisk.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/drive-removable-media.png -O drive-removable-media.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/input-keyboard.png -O input-keyboard.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-flash.png -O media-flash.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/media-optical.png -O media-optical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/printer.png -O printer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/audio-input-microphone.png -O audio-input-microphone.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/office-calendar.png -O office-calendar.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop.png -O preferences-desktop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-accessibility.png -O preferences-desktop-accessibility.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-font.png -O preferences-desktop-font.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/preferences-desktop-theme.png -O preferences-desktop-theme.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Tango/X.png -O X.png

cd ..

if [ ! -d Oxygen ]
  then
    echo "Creating folder \"Wiki\Icons\Oxygen\"..."
    mkdir Oxygen
fi

cd Oxygen

# Oxygen - Dokument
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/accessories-text-editor.png -O accessories-text-editor.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-new.png -O document-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-print.png -O document-print.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-save.png -O document-save.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-copy.png -O edit-copy.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-delete.png -O edit-delete.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-paste.png -O edit-paste.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/folder-new.png -O folder-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/folder-remote.png -O folder-remote.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-properties.png -O document-properties.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/bookmark-new.png -O bookmark-new.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-open.png -O document-open.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/document-save-as.png -O document-save-as.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-cut.png -O edit-cut.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-clear.png -O edit-clear.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-find.png -O edit-find.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/edit-select-all.png -O edit-select-all.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/folder.png -O folder.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-home.png -O user-home.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/datashow.png -O datashow.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/contents.png -O contents.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/fileclose.png -O fileclose.png

# Oxygen - Dateityp
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-x-generic.png -O audio-x-generic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/image-x-generic.png -O image-x-generic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/pdf.png -O pdf.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/text-x-generic.png -O text-x-generic.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-x-generic.png -O video-x-generic.png

# Oxygen - Navigation
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-bottom.png -O go-bottom.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-first.png -O go-first.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-jump.png -O go-jump.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-next.png -O go-next.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-top.png -O go-top.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-down.png -O go-down.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-home.png -O go-home.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-last.png -O go-last.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-previous.png -O go-previous.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/go-up.png -O go-up.png

# Oxygen - Internet
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/internet-mail.png -O internet-mail.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/internet-web-browser.png -O internet-web-browser.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/internet-telephony.png -O internet-telephony.png

# Oxygen - Netzwerk
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-wired.png -O network-wired.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-wireless.png -O network-wireless.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-connect.png -O network-connect.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/network-disconnect.png -O network-disconnect.png

# Oxygen - Listen
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/list-add.png -O list-add.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/list-remove.png -O list-remove.png

# Oxygen - Multimedia
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-eject.png -O media-eject.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playback-start.png -O media-playback-start.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-record.png -O media-record.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-seek-forward.png -O media-seek-forward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-skip-forward.png -O media-skip-forward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playlist-repeat.png -O media-playlist-repeat.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playback-pause.png -O media-playback-pause.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playback-stop.png -O media-playback-stop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-seek-backward.png -O media-seek-backward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-skip-backward.png -O media-skip-backward.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-playlist-shuffle.png -O media-playlist-shuffle.png

# Oxygen - System
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/process-stop.png -O process-stop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-search.png -O system-search.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-desktop.png -O user-desktop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-restart.png -O system-restart.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/tools_report_bug.png -O tools_report_bug.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-log-out.png -O system-log-out.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-shutdown.png -O system-shutdown.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-trash.png -O user-trash.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system_users.png -O system_users.png

# Oxygen - Ansichtsmodi
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-fullscreen.png -O view-fullscreen.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-best-fit.png -O zoom-best-fit.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-original.png -O zoom-original.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-refresh.png -O view-refresh.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-in.png -O zoom-in.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/zoom-out.png -O zoom-out.png

# Oxygen - Hardware
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-card.png -O audio-card.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-input-line.png -O audio-input-line.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/camera-photo.png -O camera-photo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/computer.png -O computer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/cpu.png -O cpu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-optical.png -O drive-optical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-removable-media-usb-pendrive.png -O drive-removable-media-usb-pendrive.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-gaming.png -O input-gaming.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-mouse.png -O input-mouse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash-memory-stick.png -O media-flash-memory-stick.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash-sd-mmc.png -O media-flash-sd-mmc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-floppy.png -O media-floppy.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-optical.png -O media-optical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-tape.png -O media-tape.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/multimedia-player-apple-ipod.png -O multimedia-player-apple-ipod.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/pda.png -O pda.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/printer.png -O printer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-display.png -O video-display.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-television.png -O video-television.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-headset.png -O audio-headset.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/audio-input-microphone.png -O audio-input-microphone.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/camera-web.png -O camera-web.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/computer-laptop.png -O computer-laptop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-harddisk.png -O drive-harddisk.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-removable-media.png -O drive-removable-media.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/drive-removable-media-usb.png -O drive-removable-media-usb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-keyboard.png -O input-keyboard.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/input-tablet.png -O input-tablet.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash.png -O media-flash.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-flash-smart-media.png -O media-flash-smart-media.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-optical-audio.png -O media-optical-audio.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/media-optical-recordable.png -O media-optical-recordable.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/modem.png -O modem.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/multimedia-player.png -O multimedia-player.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/phone.png -O phone.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/scanner.png -O scanner.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/video-projector.png -O video-projector.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/battery.png -O battery.png

# Oxygen - Einstellungen
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-other.png -O preferences-other.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop.png -O preferences-desktop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-contact-list.png -O preferences-contact-list.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-color.png -O preferences-desktop-color.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-default-applications.png -O preferences-desktop-default-applications.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-font.png -O preferences-desktop-font.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-icons.png -O preferences-desktop-icons.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-locale.png -O preferences-desktop-locale.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-notification.png -O preferences-desktop-notification.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-printer.png -O preferences-desktop-printer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-sound.png -O preferences-desktop-sound.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-theme.png -O preferences-desktop-theme.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-user.png -O preferences-desktop-user.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-kcalc-constants.png -O preferences-kcalc-constants.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-bluetooth.png -O preferences-system-bluetooth.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-network-sharing.png -O preferences-system-network-sharing.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-time.png -O preferences-system-time.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-personal.png -O preferences-desktop-personal.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-filetype-association.png -O preferences-desktop-filetype-association.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/user-identity.png -O user-identity.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-session-services.png -O preferences-system-session-services.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-windows.png -O preferences-system-windows.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-power-management.png -O preferences-system-power-management.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-login.png -O preferences-system-login.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-plugin.png -O preferences-plugin.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-wallpaper.png -O preferences-desktop-wallpaper.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-user-password.png -O preferences-desktop-user-password.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-text-to-speech.png -O preferences-desktop-text-to-speech.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-screensaver.png -O preferences-desktop-screensaver.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-peripherals.png -O preferences-desktop-peripherals.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-mouse.png -O preferences-desktop-mouse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-keyboard.png -O preferences-desktop-keyboard.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-gaming.png -O preferences-desktop-gaming.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-display.png -O preferences-desktop-display.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-cryptography.png -O preferences-desktop-cryptography.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-desktop-accessibility.png -O preferences-desktop-accessibility.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system-network.png -O preferences-system-network.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-system.png -O preferences-system.png

# Oxygen - Anwendungen
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/k3b.png -O k3b.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/konversation.png -O konversation.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/partitionmanager.png -O partitionmanager.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/kaffeine.png -O kaffeine.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/hwinfo.png -O hwinfo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/nepomuk.png -O nepomuk.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/preferences-activities.png -O preferences-activities.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/k3b_1.png -O k3b_1.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/kontact.png -O kontact.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/knotes.png -O knotes.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/digikam.png -O digikam.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/akonadi.png -O akonadi.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/konsole.png -O konsole.png

# Oxygen - Diverses
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/office-calendar.png -O office-calendar.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/X.png -O X.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/terminal.png -O terminal.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/kde.png -O kde.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/plasma.png -O plasma.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/security-high.png -O security-high.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/security-low.png -O security-low.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications-games.png -O applications-games.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-run.png -O system-run.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/face-smile.png -O face-smile.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/view-calendar-day.png -O view-calendar-day.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/help-browser.png -O help-browser.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/emblem-favorite.png -O emblem-favorite.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/utilities-file-archiver.png -O utilities-file-archiver.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications-internet.png -O applications-internet.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications-other.png -O applications-other.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/security-medium.png -O security-medium.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/dialog-ok-apply.png -O dialog-ok-apply.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/object-locked.png -O object-locked.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/system-software-update.png -O system-software-update.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/get-hot-new-stuff.png -O get-hot-new-stuff.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Oxygen/applications_engineering.png -O applications_engineering.png

cd ..

if [ ! -d Portal ]
  then
    echo "Creating folder \"Wiki\Icons\Portal\"..."
    mkdir Portal
fi

cd Portal

wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/portal.png -O portal.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/ikhaya.png -O ikhaya.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/ubuntuusers.png -O ubuntuusers.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/community.png -O community.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-preferences.png -O usercp-preferences.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-profile.png -O usercp-profile.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-wikipage.png -O usercp-wikipage.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/anchor.png -O anchor.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/mark.png -O mark.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/picture.png -O picture.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/topic-solved-locked.png -O topic-solved-locked.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/forum.png -O forum.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/planet.png -O planet.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/wiki.png -O wiki.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/wochenrueckblick.png -O wochenrueckblick.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-password.png -O usercp-password.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/usercp-subscriptions.png -O usercp-subscriptions.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/code.png -O code.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/download.png -O download.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/userlink.png -O userlink.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/wikilink.png -O wikilink.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/expand.png -O expand.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/Icons/Portal/ubuntu-community.png -O ubuntu-community.png

cd ${PROJECT}

sleep 2
echo "DOWNLOAD FINISHED"
