#!/bin/bash
# GetIWLs from ubuntuusers.de
# this file is part of InyokaEdit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

PROJECT="${1}"

if [ "${PROJECT}" == "" ]
  then
    echo "USAGE: ./`basename $0` [STYLES FOLDER]"
    exit
fi

if [ ! -d ${PROJECT} ]
  then
    echo "Creating styles main folder..."
    mkdir -p ${PROJECT}
fi

cd ${PROJECT}

if [ ! -d styles ]
  then
    echo "Creating folder \"styles\"..."
    mkdir styles
fi

cd styles

echo "Downloading css files..."
rm main.css
rm markup2.css
rm wiki.css
rm highlight.css
rm markup.css

wget -nv http://static.cdn.ubuntu-de.org/style/main.css
wget -nv http://static.cdn.ubuntu-de.org/style/markup.css
mv markup.css markup2.css
wget -nv http://static.cdn.ubuntu-de.org/style/wiki.css
wget -nv http://static.cdn.ubuntu-de.org/style/highlight.css
wget -nv http://ubuntuusers.de/markup.css

echo "Replace static paths..."
## Paths
_r1="http://static.cdn.ubuntu-de.org"
_r2="http://media.cdn.ubuntu-de.org/wiki/attachments/[0-9][0-9]/[0-9][0-9]"
_r3="../img/interwiki"
## Escape path for sed using bash find and replace
_r1="${_r1//\//\\/}"
_r2="${_r2//\//\\/}"
_r3="${_r3//\//\\/}"
## Replace paths
sed -e "s/${_r1}/../g" -i markup.css
sed -e "s/${_r2}/${_r3}/g" -i markup.css

cd ..

if [ ! -d img ]
  then
    echo "Creating folder \"img\"..."
    mkdir img
fi

cd img

if [ ! -d interwiki ]
  then
    echo "Creating folder \"interwiki\"..."
    mkdir interwiki
fi

cd interwiki

wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/archwiki.png -O archwiki.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/askubuntu.png -O askubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/atomicgamer.png -O atomicgamer.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/bitbucket.png -O bitbucket.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/blogspot.png -O blogspot.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/brainstorm.png -O brainstorm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/bug.png -O bug.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonical.png -O canonical.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonicalblog.png -O canonicalblog.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/canonicalvoices.png -O canonicalvoices.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debian.png -O debian.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debianbug.png -O debianbug.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/debian_de.png -O debian_de.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/derstandard.png -O derstandard.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/desura.png -O desura.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/diaspora.png -O diaspora.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/dropbox.png -O dropbox.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/duckduckgo.png -O duckduckgo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ean.png -O ean.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/edubuntu.png -O edubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/fb.png -O fb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freecode.png -O freecode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freedesktop.png -O freedesktop.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freenode.png -O freenode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/freshmeat.png -O freshmeat.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gameolith.png -O gameolith.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnomeapps.png -O gnomeapps.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnomeprojects.png -O gnomeprojects.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/getdeb.png -O getdeb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/github.png -O github.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gnome.png -O gnome.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gog.png -O gog.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/googlecode.png -O googlecode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/gplus.png -O gplus.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/heise.png -O heise.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/holarse.png -O holarse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/humble.png -O humble.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/iawm.png -O iawm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ikhaya.png -O ikhaya.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/indiedb.png -O indiedb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/identica.png -O identica.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/isbn.png -O isbn.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ixquick.png -O ixquick.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kdebugs.png -O kdebugs.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu.png -O kubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu-de.png -O kubuntu-de.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/kubuntu_doc.png -O kubuntu_doc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lastfm.png -O lastfm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/launchpad.png -O launchpad.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lgdb.png -O lgdb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/liflg.jpg -O liflg.jpg
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/linuxgaming.png -O linuxgaming.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lpcode.png -O lpcode.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lpuser.png -O lpuser.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/lubuntu.png -O lubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/man.png -O man.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/man_de.png -O man_de.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ml.png -O ml.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/moby.png -O moby.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/moddb.png -O moddb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/mythbuntu.png -O mythbuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/omgubuntu.png -O omgubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/opensuse.jpg -O opensuse.jpg
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/osm.png -O osm.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/packages.png -O packages.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/pdf.png -O pdf.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/playdeb.png -O playdeb.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/prolinux.png -O prolinux.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/quakenet.png -O quakenet.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/sourceforge.png -O sourceforge.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/sourceforge2.png -O sourceforge2.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/startpage.png -O startpage.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/steam.png -O steam.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/team.png -O team.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ticket.png -O ticket.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/twitter.png -O twitter.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu.png -O ubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntuapps.png -O ubuntuapps.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_forum.png -O uf_forum.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_member.png -O uf_member.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/uf_thread.png -O uf_thread.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntufridge.png -O ubuntufridge.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntudiscourse.png -O ubuntudiscourse.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubunturesources.png -O ubunturesources.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntumate.png -O ubuntumate.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntusub.png -O ubuntusub.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntuone.png -O ubuntuone.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntugnome.png -O ubuntugnome.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntustudio.png -O ubuntustudio.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu_doc.png -O ubuntu_doc.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/ubuntu_fr.png -O ubuntu_fr.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/user.png -O user.png
cp user.png user-xmas.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/vimeo.png -O vimeo.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikibooks.png -O wikibooks.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikibooks_en.png -O wikibooks_en.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikimedia.png -O wikimedia.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikipedia.png -O wikipedia.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wikipedia_en.png -O wikipedia_en.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/wordpress.png -O wordpress.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/xfcedocs.png -O xfcedocs.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/xubuntu.png -O xubuntu.png
wget -nv http://wiki.ubuntuusers.de/_image?target=Wiki/InterwikiMap/youtube.png -O youtube.png

wget -nv http://static.cdn.ubuntu-de.org/img/interwiki/search.png -O search.png
wget -nv http://media.cdn.ubuntu-de.org/wiki/attachments/17/43/ppa.png -O ppa.png

echo "IWL DOWNLOAD FINISHED"
