# SPDX-FileCopyrightText: 2011-2025 The InyokaEdit developers
# SPDX-License-Identifier: GPL-3.0-or-later

macro(set_preview_dependencies target_name)
    if(NOT INY_PREVIEW)
        find_package(${QT_MAIN_VERSION} QUIET ${QT_MINIMUM_VERSION} OPTIONAL_COMPONENTS WebEngineWidgets)
        if(Qt6WebEngineWidgets_FOUND)
            target_link_libraries(${target_name} PRIVATE ${QT_MAIN_VERSION}::WebEngineWidgets)
            target_compile_definitions(${target_name} PRIVATE USEQTWEBENGINE)
            message(STATUS "Qt webenginewidgets module found!")
        else()
            target_compile_definitions(${target_name} PRIVATE NOPREVIEW)
            message(STATUS "QtWebEngine not found! Building without included preview.")
        endif()
    else()
        message(STATUS "Preview set to \"${INY_PREVIEW}\"")
        if(INY_PREVIEW STREQUAL "useqtwebengine")
            find_package(${QT_MAIN_VERSION} ${QT_MINIMUM_VERSION} REQUIRED WebEngineWidgets)
            target_link_libraries(${target_name} PRIVATE ${QT_MAIN_VERSION}::WebEngineWidgets)
            target_compile_definitions(${target_name} PRIVATE USEQTWEBENGINE)
        else()
            target_compile_definitions(${target_name} PRIVATE NOPREVIEW)
            message(STATUS "Building without included preview.")
        endif()
    endif()
endmacro()
