name: "AppImage"

# manual trigger
on:
  workflow_dispatch:

env:
  ARCH: "x86_64"

jobs:
  AppImage_Ubuntu22-04:
    name: AppImage Ubuntu 22.04 Qt 6.2
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set global env
      run: |
       echo "BASE_DIR=$(pwd)" >> $GITHUB_ENV
       echo "LINUXDEPLOY_OUTPUT_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Install Dependencies
      run: sudo apt update && sudo apt install qt6-base-dev qmake6 qt6-l10n-tools qt6-tools-dev qt6-tools-dev-tools qt6-webengine-dev qt6-webengine-dev-tools qt6-wayland libgl-dev libhunspell-dev appstream libfuse2

    - name: Download linuxdeploy
      run: |
       wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-"$ARCH".AppImage"
       chmod a+x linuxdeploy-"$ARCH".AppImage
       LINUXDEPLOY_BIN=${PWD}/linuxdeploy-"$ARCH".AppImage

    - name: Download linuxdeployqt-plugin-appimage
      run: |
       wget -c -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-"$ARCH".AppImage"
       chmod a+x linuxdeploy-plugin-appimage-"$ARCH".AppImage

    - name: Download linuxdeployqt-plugin-qt
      run: |
       wget -c -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-"$ARCH".AppImage"
       chmod a+x linuxdeploy-plugin-qt-"$ARCH".AppImage

    - name: Download ffsend
      run: |
       FFSEND_VERSION=$(curl --silent https://api.github.com/repos/timvisee/ffsend/releases/latest | sed -Ene '/^ *"tag_name": *"(v.+)",$/s//\1/p')
       wget -c -nv "https://github.com/timvisee/ffsend/releases/download/$FFSEND_VERSION/ffsend-$FFSEND_VERSION-linux-x64-static"
       mv ./ffsend-* ./ffsend
       chmod a+x ./ffsend

    - name: Clone ubuntuusers community repository
      run: |
       git clone -b community --single-branch https://github.com/inyokaproject/inyokaedit.git community

    - name: Compile
      run: |
       cmake -B build-cmake -DCMAKE_PREFIX_PATH=/usr/include/x86_64-linux-gnu/qt6/ -DINY_COMMUNITY=community/ubuntuusers_de
       cmake --build build-cmake -- -j$(nproc)
       DESTDIR=${PWD}/AppDir cmake --install build-cmake

    - name: Create AppImage
      run: |
       mkdir -p ${BASE_DIR}/out
       export EXTRA_PLATFORM_PLUGINS="libqwayland-generic.so"
       export EXTRA_QT_MODULES="waylandcompositor"
       export QMAKE=/usr/lib/qt6/bin/qmake
       ${PWD}/linuxdeploy-"$ARCH".AppImage --appdir ${PWD}/AppDir --plugin qt --output appimage
       mv -v InyokaEdit-*.AppImage ${BASE_DIR}/out

    - name: Upload AppImage
      run: |
       ./ffsend upload ${BASE_DIR}/out/InyokaEdit-*.AppImage
