name: "CI"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  AppImage_Ubuntu18-04:
    name: AppImage Ubuntu 18.04 Qt 5.9
    runs-on: ubuntu-18.04
    env:
      QT_SELECT: qt5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt update && sudo apt install qtbase5-dev qt5-qmake qttools5-dev-tools libqt5webkit5-dev libhunspell-dev

    - name: Download linuxdeployqt
      run: |
       wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
       chmod a+x linuxdeployqt-continuous-x86_64.AppImage
       unset QTDIR ; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
       export VERSION=$(git rev-parse --short HEAD)  # linuxdeployqt uses this for naming the file

    - name: Download ffsend
      run: |
       FFSEND_VERSION=$(curl --silent https://api.github.com/repos/timvisee/ffsend/releases/latest | sed -Ene '/^ *"tag_name": *"(v.+)",$/s//\1/p')
       wget -c -nv "https://github.com/timvisee/ffsend/releases/download/$FFSEND_VERSION/ffsend-$FFSEND_VERSION-linux-x64-static"
       mv ./ffsend-* ./ffsend
       chmod a+x ./ffsend

    - name: Clone ubuntuusers community repository
      run: |
       git clone -b community --single-branch https://github.com/inyokaproject/inyokaedit.git community

    - name: Compile
      run: |
       ./configure --prefix=/usr --community=ubuntuusers_de
       make all -j$(nproc)
       make DESTDIR=appdir install
       find appdir

    - name: Create AppImage
      run: |
       ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -bundle-non-qt-libs -extra-plugins=iconengines,platformthemes/libqgtk3.so
       find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq

    - name: Upload AppImage
      run: |
       ./ffsend upload InyokaEdit-*-x86_64.AppImage

  AppImage_Ubuntu18-04_Qt5-15:
    name: AppImage Ubuntu 18.04 Qt 5.15
    runs-on: ubuntu-18.04
    env:
      QT_SELECT: qt5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
       sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic -y
       sudo apt-get update -qq
       sudo apt-get -y install qt515base qt515tools qt515webengine libhunspell-dev libgl1-mesa-dev

    - name: Download linuxdeployqt
      run: |
       wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
       chmod a+x linuxdeployqt-continuous-x86_64.AppImage
       export VERSION=$(git rev-parse --short HEAD)  # linuxdeployqt uses this for naming the file

    - name: Download ffsend
      run: |
       FFSEND_VERSION=$(curl --silent https://api.github.com/repos/timvisee/ffsend/releases/latest | sed -Ene '/^ *"tag_name": *"(v.+)",$/s//\1/p')
       wget -c -nv "https://github.com/timvisee/ffsend/releases/download/$FFSEND_VERSION/ffsend-$FFSEND_VERSION-linux-x64-static"
       mv ./ffsend-* ./ffsend
       chmod a+x ./ffsend

    - name: Clone ubuntuusers community repository
      run: |
       git clone -b community --single-branch https://github.com/inyokaproject/inyokaedit.git community

    - name: Compile
      run: |
       source /opt/qt*/bin/qt*-env.sh || true
       ./configure --prefix=/usr --community=ubuntuusers_de
       make all -j$(nproc)
       make DESTDIR=appdir install
       find appdir

    - name: Create AppImage
      run: |
       source /opt/qt*/bin/qt*-env.sh || true
       ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -bundle-non-qt-libs -extra-plugins=iconengines,platformthemes/libqgtk3.so
       find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
      env:
        # Unset environment variables
        QTDIR:
        QT_PLUGIN_PATH:
        LD_LIBRARY_PATH:

    - name: Upload AppImage
      run: |
       ./ffsend upload InyokaEdit-*-x86_64.AppImage
