name: "Clang-Format-Check"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './application ./application/parser ./application/templates ./plugins/highlighter ./plugins/hotkey ./plugins/spellchecker-hunspell ./plugins/spellchecker/nuspell ./plugins/uu_knowledgebox ./plugins/uu_tabletemplate'
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: Google
